[build]
builder = "DOCKERFILE"
dockerfilePath = "api/Dockerfile"
watchPatterns = ["api/**"]

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/api/v1/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
